name: yts_movie_finder

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true